CREATE TABLE PUBLISHER(NAME VARCHAR(20) PRIMARY KEY, ADDRESS VARCHAR(20),PHONE VARCHAR(10)); 
INSERT INTO PUBLISHER VALUES ('Pearson','BANGALORE', 9989076587);  
 

CREATE TABLE LIBRARY_BRANCH(BRANCH_ID INT PRIMARY KEY,BRANCH_NAME VARCHAR(20),ADDRESS VARCHAR(20)); 
INSERT INTO LIBRARY_BRANCH VALUES (101,'PEARSON','BANGALORE'); 

 
CREATE TABLE BOOK(BOOK_ID INT PRIMARY KEY,TITLE VARCHAR(20), PUBLISHER_NAME VARCHAR(20) REFERENCES PUBLISHER(NAME) ON DELETE CASCADE, PUB_YEAR VARCHAR(20)); 
INSERT INTO BOOK VALUES (101,'DBMS', 'Pearson',2016); 

CREATE TABLE BOOK_AUTHORS(BOOK_ID INT REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,AUTHOR_NAME VARCHAR(20),PRIMARY KEY (BOOK_ID,AUTHOR_NAME)); 
INSERT INTO BOOK_AUTHORS VALUES(101 ,'SHAMAKANTH'); 

 
CREATE TABLE BOOK_COPIES(BOOK_ID INT REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,BRANCH_ID INT REFERENCES LIBRARY_BRANCH(BRANCH_ID)ON DELETE CASCADE, NO_OF_COPIES INT, PRIMARY KEY(BOOK_ID,BRANCH_ID)); 
INSERT INTO BOOK_COPIES VALUES(101, 101,200); 
 
CREATE TABLE BOOK_LENDING(BOOK_ID INT REFERENCES BOOK(BOOK_ID) ON DELETE CASCADE,BRANCH_ID INT REFERENCES LIBRARY_BRANCH(BRANCH_ID)ON DELETE CASCADE,CARD_NO INT, DATE_OUT DATE, DUE_DATE DATE,PRIMARY KEY(BOOK_ID,BRANCH_ID,CARD_NO));
INSERT INTO BOOK_LENDING VALUES(101,101,02,'2017-08-17','2017-08-25'); 


-- Query 1: 
SELECT B.Book_id,Title,P.Name,Author_Name,Branch_id,No_of_copies FROM Book B, Book_Authors BA,Publisher P,Book_Copies BC WHERE B.Book_id=BA.Book_id AND B.Publisher_Name=P.Name AND B.Book_id=BC.Book_id; 


-- Query 2: 
SELECT Card_No,COUNT(*) FROM BOOK_LENDING WHERE Date_out BETWEEN '2017-01-01' AND '2017-06-30' GROUP BY Card_No HAVING COUNT(*)>3; 


-- Query 3: 
DELETE FROM BOOK WHERE Book_id='101'; 

-- Query 4: 
CREATE VIEW V_PUBLICATION AS SELECT PUB_YEAR FROM BOOK;

-- Query 5: 
CREATE VIEW TOTAL_BOOK_COPIES(Book_id,Total_Books) AS Select Book_id, SUM(No_of_copies) FROM BOOK_COPIES GROUP BY Book_id; 
