CREATE TABLE ACTOR( ACT_ID INT PRIMARY KEY, ACT_NAME VARCHAR(20), ACT_GENDER CHAR); 
INSERT INTO ACTOR VALUES(1,'GANESH','M');

 
CREATE TABLE DIRECTOR( DIR_ID INT PRIMARY KEY, DIR_NAME VARCHAR(20), DIR_PHONE VARCHAR(10)); 
INSERT INTO DIRECTOR VALUES(101 ,'DORAI BHAGAVAN',9408757465);
 
CREATE TABLE MOVIES( MOV_ID INT PRIMARY KEY, MOV_TITLE VARCHAR(30), MOV_YEAR VARCHAR(4), MOV_LANG VARCHAR(20), DIR_ID INT, FOREIGN KEY(DIR_ID) REFERENCES DIRECTOR(DIR_ID)); 
INSERT INTO MOVIES VALUES(11,'MUNGARU MALE',2008,'KANNADA',102); 

 
CREATE TABLE MOVIE_CAST( ACT_ID INT, MOV_ID INT,ROLE VARCHAR(20), PRIMARY KEY(ACT_ID,MOV_ID), FOREIGN KEY(ACT_ID) REFERENCES ACTOR(ACT_ID),FOREIGN KEY(MOV_ID) REFERENCES MOVIES(MOV_ID)); 
INSERT INTO MOVIE_CAST VALUES(1,11,'HERO');  


CREATE TABLE RATING( MOV_ID INT, REV_STARS INT, PRIMARY KEY(MOV_ID), FOREIGN KEY(MOV_ID) REFERENCES MOVIES(MOV_ID)); 
NSERT INTO RATING VALUES(11,5); 

Query 1: 
select MOV_TITLE from MOVIES where DIR_ID=(select DIR_ID from director where DIR_NAME = 'HITCHCOCK'); 

Query 2: 
select M.MOV_ID,MOV_TITLE from MOVIES M,MOVIE_CAST MC where M.MOV_ID=MC.MOV_ID and ACT_ID in ( select ACT_ID from MOVIE_CASt group by ACT_ID having count(*)>=2) order by M.MOV_ID; 

Query 3: 
select A.ACT_ID,ACT_NAME from ACTOR A, MOVIES M, MOVIE_CAST MC where A.ACT_ID= MC.ACT_ID and M.MOV_ID =MC.MOV_ID and MOV_YEAR> 2015 INTERSECT select A.ACT_ID,ACT_NAMe from ACTOR A, MOVIES M, MOVIE_CAST MC where A.ACT_ID =MC.ACT_ID and M.MOV_ID =MC.MOV_ID and MOV_YEAR< 2000; 

Query 4: 
select MOV_TITLE,REV_STARS from MOVIES M, RATING R where M.MOV_ID= R.MOV_ID and REV_STARS in (select max(REV_STARS) from rating) order by MOV_TITLE;

Query 5: 
update rating set REV_STARS= 5 where MOV_ID IN (select MOV_ID from MOVIES M, DIRECTOR D where M.DIR_ID =D.DIR_ID and DIR_NAME='STEVEN SPIELBERG');  