CREATE TABLE SALESMAN (SALESMAN_ID INTEGER PRIMARY KEY, NAME VARCHAR (20),CITY VARCHAR (30),COMMISSION VARCHAR (20)); 
INSERT INTO SALESMAN VALUES (1000, 'JOHN','BANGALORE',2000); 

 
CREATE TABLE CUSTOMER (CUSTOMER_ID INTEGER PRIMARY KEY, CUST_NAME VARCHAR (20),CITY VARCHAR (30), GRADE INT, SALESMAN_ID INTEGER,FOREIGN KEY(SALESMAN_ID) REFERENCES SALESMAN (SALESMAN_ID) ON 
DELETE SET NULL); 
INSERT INTO CUSTOMER VALUES (2000, 'SUNIL','MANGALORE', 1, 1000); 

 
CREATE TABLE ORDERS (ORD_NO INTEGER PRIMARY KEY, PURCHASE_AMT INTEGER,ORD_DATE DATE, CUSTOMER_ID INTEGER, SALESMAN_ID INTEGER, FOREIGN KEY(SALESMAN_ID)REFERENCES SALESMAN (SALESMAN_ID) ON DELETE CASCADE,FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID));
INSERT INTO ORDERS VALUES(101, 7000, '2017-08-21, 2002, 1005);


Query 1: 
SELECT COUNT(Customer_id) FROM CUSTOMER WHERE GRADE>(SELECT AVG(GRADE) FROM CUSTOMER WHERE CITY='BANGALORE');

Query 2: 
SELECT S.Salesman_id,S.Name FROM SALESMAN S,CUSTOMER C WHERE S.Salesman_id=C.Salesman_id GROUP BY S.Salesman_id,S.Name HAVING COUNT(Customer_id)>1;  

Query 3: 
SELECT S.Salesman_id FROM SALESMAN S,CUSTOMER C WHERE S.Salesman_id=C.Salesman_id AND S.City!=C.City UNION SELECT S.Salesman_id FROM SALESMAN S,CUSTOMER C WHERE S.Salesman_id=C.Salesman_id AND S.City=C.City; 

Query 4: 
create view SALESMAN_WITH_MAX_ORDER as select B.ORD_DATE, A.SALESMAN_ID, A.NAME from salesman a, orders b where a.salesman_id=b.salesman_id and b.purchase_amt=(select max(purchase_amt) from orders c where c.ord_date=b.ord_date); 

Query 5: 
DELETE FROM SALESMAN WHERE Salesman_id=1000; 
